version: "3.7"
services:
    store:
        build: ../../db
        ports: 
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        networks: 
            - big-store-net

    hub:
        build: ../../hub
        ports: 
            - 80:60001
        networks: 
            - big-store-net

    events:
        image: rabbitmq:latest
        ports: 
            - 5672:5672
        networks: 
            - big-store-net

    cluster-companion:
        build: ../../cluster-companion
        restart: on-failure
        environment:
            - CACHE_HOST=big-store_cache_1
            - BS_ENV=PROD
        # ports:
            # - 60010-60150:60001
        networks:
            - big-store-net
            # - cache-net
    cache:
        image: redis
        # ports:
        #     - 6379:6379
        networks:
            - big-store-net
            # - cache-net


networks:
    big-store-net: 
