version: "3.7"
services:
  cluster-companion:
    build: .
    ports:
      - 60010:60010
    networks:
      - cluster-companion-net
  cache:
    image: redis
    ports:
      - 6379:6379
    networks:
      - cluster-companion-net
  store:
    build: ./../db
    networks:
      - cluster-companion-net
networks:
  cluster-companion-net:

