version: "3.7"
services:
  cluster-companion:
    build: .
    ports:
      - 60001:60001
    networks:
      - cluster-companion-net
    links:
      - cache:redis
  cache:
    image: redis
    ports:
      - 6379:6379
    networks:
      - cluster-companion-net
networks:
  cluster-companion-net:

